---
# This playbook deploys a gemini master.

- hosts: gem-masters
  sudo: yes
  roles:
    - ansible-controller
    - dnsmasq
    - tftp
    - httpd
    - coreos-cloudinit
  tags:
    - ansible-controller
    - dnsmasq
    - tftp
    - httpd
    - coreos-cloudinit
